package yadrone;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import ImageProcessing.CircleDetection;
import ImageProcessing.ProcessedImagePanel;
import de.yadrone.base.IARDrone;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.TimerTask;
import javax.imageio.ImageIO;
import javax.swing.UIManager;

/**
 *
 * @author Morten
 */
public class DroneGUI extends javax.swing.JFrame implements Runnable
{

    private VideoListener v1;
    private NavDataListener navData;

    private DroneControl cont;
    private IARDrone drone;
    private Regulator regulator;
    private final ProcessedImagePanel pil;
    private final CircleDetection cd;

    /**
     * Creates new form Test2DoneGUI
     */
    public DroneGUI(IARDrone drone,
            DroneControl cont,
            ProcessedImagePanel pil,
            TimerTask regulator,
            CircleDetection cd)
    {
        this.drone = drone;
        this.cont = cont;
        this.pil = pil;
        this.regulator = (Regulator) regulator;
        this.cd = cd;
        v1 = new VideoListener(drone);
        navData = new NavDataListener(drone);
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (Exception e) {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            }
            catch (Exception ex) {
            }

        }
        initComponents();
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        VideoStreamViewer = v1;
        ImageProcessViewer = pil;
        ButtonPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        yawTextField = new javax.swing.JTextField();
        pitchTextField = new javax.swing.JTextField();
        rollTextField = new javax.swing.JTextField();
        altitudeTextField = new javax.swing.JTextField();
        batTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        yawPropotionalTextField = new javax.swing.JTextField();
        yawPropotionalTextField.setText("Propotional: " + regulator.getKpYaw());
        jLabel1 = new javax.swing.JLabel();
        yawIntegralTextField = new javax.swing.JTextField();
        yawIntegralTextField.setText("Integral: " + regulator.getKiYaw());
        yawDerivateTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        snapshotButton = new javax.swing.JButton();
        valueUpperTF = new javax.swing.JTextField();
        saturationUpperTF = new javax.swing.JTextField();
        hueUpperTF = new javax.swing.JTextField();
        valueLowerTF = new javax.swing.JTextField();
        SaturationLowerTF = new javax.swing.JTextField();
        hueLowerTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        landButton = new javax.swing.JButton();
        autoButton = new javax.swing.JButton();
        manButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VideoStreamViewer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout VideoStreamViewerLayout = new javax.swing.GroupLayout(VideoStreamViewer);
        VideoStreamViewer.setLayout(VideoStreamViewerLayout);
        VideoStreamViewerLayout.setHorizontalGroup(
            VideoStreamViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        VideoStreamViewerLayout.setVerticalGroup(
            VideoStreamViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        ImageProcessViewer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ImageProcessViewerLayout = new javax.swing.GroupLayout(ImageProcessViewer);
        ImageProcessViewer.setLayout(ImageProcessViewerLayout);
        ImageProcessViewerLayout.setHorizontalGroup(
            ImageProcessViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        ImageProcessViewerLayout.setVerticalGroup(
            ImageProcessViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ButtonPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Navigation data");

        yawTextField.setText("Yaw:");

        pitchTextField.setText("Pitch:");

        rollTextField.setText("Roll:");

        altitudeTextField.setText("Altitude:");

        batTextField.setText("Battery Status:");

        javax.swing.GroupLayout ButtonPanel1Layout = new javax.swing.GroupLayout(ButtonPanel1);
        ButtonPanel1.setLayout(ButtonPanel1Layout);
        ButtonPanel1Layout.setHorizontalGroup(
            ButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(ButtonPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ButtonPanel1Layout.createSequentialGroup()
                        .addGroup(ButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(altitudeTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(yawTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pitchTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(batTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(rollTextField))))
                .addContainerGap())
        );
        ButtonPanel1Layout.setVerticalGroup(
            ButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pitchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(441, 441, 441)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PID gains");

        yawPropotionalTextField.setText("Propotional 0.0");
        yawPropotionalTextField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                yawPropotionalTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                yawPropotionalTextFieldFocusLost(evt);
            }
        });
        yawPropotionalTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yawPropotionalTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Yaw");

        yawIntegralTextField.setText("Integral 0.0");
        yawIntegralTextField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                yawIntegralTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                yawIntegralTextFieldFocusLost(evt);
            }
        });
        yawIntegralTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yawIntegralTextFieldActionPerformed(evt);
            }
        });

        yawDerivateTextField.setText("Derivate 0.0");
        yawDerivateTextField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                yawDerivateTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                yawDerivateTextFieldFocusLost(evt);
            }
        });
        yawDerivateTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yawDerivateTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yawIntegralTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yawPropotionalTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(yawDerivateTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yawPropotionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yawIntegralTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yawDerivateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        snapshotButton.setText("Snapshot");
        snapshotButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                snapshotButtonActionPerformed(evt);
            }
        });

        valueUpperTF.setText("V upper threshold:");
        valueUpperTF.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                valueUpperTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                valueUpperTFFocusLost(evt);
            }
        });
        valueUpperTF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                valueUpperTFActionPerformed(evt);
            }
        });

        saturationUpperTF.setText("S upper threshold:");
        saturationUpperTF.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                saturationUpperTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                saturationUpperTFFocusLost(evt);
            }
        });
        saturationUpperTF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saturationUpperTFActionPerformed(evt);
            }
        });

        hueUpperTF.setText("H upper threshold:");
        hueUpperTF.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                hueUpperTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                hueUpperTFFocusLost(evt);
            }
        });
        hueUpperTF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                hueUpperTFActionPerformed(evt);
            }
        });

        valueLowerTF.setText("V lower threshold:");
        valueLowerTF.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                valueLowerTFFocusGained(evt);
            }
        });
        valueLowerTF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                valueLowerTFActionPerformed(evt);
            }
        });

        SaturationLowerTF.setText("S lower threshold:");
        SaturationLowerTF.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                SaturationLowerTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                SaturationLowerTFFocusLost(evt);
            }
        });
        SaturationLowerTF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SaturationLowerTFActionPerformed(evt);
            }
        });

        hueLowerTF.setText("H lower threshold:");
        hueLowerTF.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                hueLowerTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                hueLowerTFFocusLost(evt);
            }
        });
        hueLowerTF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                hueLowerTFActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Image Processing");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(snapshotButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(valueLowerTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(hueLowerTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaturationLowerTF, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(168, 168, 168)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saturationUpperTF)
                            .addComponent(hueUpperTF)
                            .addComponent(valueUpperTF))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hueLowerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hueUpperTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaturationLowerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saturationUpperTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueUpperTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLowerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snapshotButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        landButton.setText("Land");
        landButton.setFocusPainted(false);
        landButton.setFocusable(false);
        landButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                landButtonActionPerformed(evt);
            }
        });

        autoButton.setText("Autonomous mode");
        autoButton.setFocusPainted(false);
        autoButton.setFocusable(false);
        autoButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                autoButtonActionPerformed(evt);
            }
        });

        manButton.setText("Manual mode");
        manButton.setFocusPainted(false);
        manButton.setFocusable(false);
        manButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                manButtonActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mode selection");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(manButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(landButton, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(autoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manButton)
                    .addComponent(autoButton)
                    .addComponent(landButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ImageProcessViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VideoStreamViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VideoStreamViewer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ImageProcessViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );

        VideoStreamViewer.getAccessibleContext().setAccessibleName("");
        ImageProcessViewer.getAccessibleContext().setAccessibleName("ImageProcessViewer");
        ImageProcessViewer.getAccessibleContext().setAccessibleDescription("The Processed Images");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manButtonActionPerformed
        cont.setMode(DroneControl.DroneMode.MAN_MODE);
        manButton.setForeground(Color.GREEN);
        autoButton.setForeground(Color.BLACK);
        landButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_manButtonActionPerformed

    private void autoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoButtonActionPerformed
        cont.setMode(DroneControl.DroneMode.AUTO_MODE);
        manButton.setForeground(Color.BLACK);
        autoButton.setForeground(Color.GREEN);
        landButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_autoButtonActionPerformed

    private void landButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landButtonActionPerformed
        cont.setMode(DroneControl.DroneMode.LANDING);
        manButton.setForeground(Color.BLACK);
        autoButton.setForeground(Color.BLACK);
        landButton.setForeground(Color.GREEN);
    }//GEN-LAST:event_landButtonActionPerformed

    private void yawPropotionalTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yawPropotionalTextFieldActionPerformed
    {//GEN-HEADEREND:event_yawPropotionalTextFieldActionPerformed
        try {
            regulator.setKpYaw(Float.valueOf(yawPropotionalTextField.getText()));
        }
        catch (Exception e) {
        }

    }//GEN-LAST:event_yawPropotionalTextFieldActionPerformed

    private void yawDerivateTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yawDerivateTextFieldActionPerformed
    {//GEN-HEADEREND:event_yawDerivateTextFieldActionPerformed
        try {
            regulator.setKdYaw(Float.valueOf(yawDerivateTextField.getText()));
        }
        catch (Exception e) {
        }    }//GEN-LAST:event_yawDerivateTextFieldActionPerformed

    private void yawIntegralTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yawIntegralTextFieldActionPerformed
    {//GEN-HEADEREND:event_yawIntegralTextFieldActionPerformed
        try {
            regulator.setKiYaw(Float.valueOf(yawIntegralTextField.getText()));
        }
        catch (Exception e) {
        }    }//GEN-LAST:event_yawIntegralTextFieldActionPerformed

    private void yawDerivateTextFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_yawDerivateTextFieldFocusGained
    {//GEN-HEADEREND:event_yawDerivateTextFieldFocusGained
        yawDerivateTextField.setText("");
    }//GEN-LAST:event_yawDerivateTextFieldFocusGained

    private void yawIntegralTextFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_yawIntegralTextFieldFocusGained
    {//GEN-HEADEREND:event_yawIntegralTextFieldFocusGained
        yawIntegralTextField.setText("");
    }//GEN-LAST:event_yawIntegralTextFieldFocusGained

    private void yawPropotionalTextFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_yawPropotionalTextFieldFocusGained
    {//GEN-HEADEREND:event_yawPropotionalTextFieldFocusGained
        yawPropotionalTextField.setText("");
    }//GEN-LAST:event_yawPropotionalTextFieldFocusGained

    private void yawPropotionalTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_yawPropotionalTextFieldFocusLost
    {//GEN-HEADEREND:event_yawPropotionalTextFieldFocusLost
        yawPropotionalTextField.setText("Propotional: " + regulator.getKpYaw());
    }//GEN-LAST:event_yawPropotionalTextFieldFocusLost

    private void yawIntegralTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_yawIntegralTextFieldFocusLost
    {//GEN-HEADEREND:event_yawIntegralTextFieldFocusLost
        yawIntegralTextField.setText("Integral: " + regulator.getKiYaw());
     }//GEN-LAST:event_yawIntegralTextFieldFocusLost

    private void yawDerivateTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_yawDerivateTextFieldFocusLost
    {//GEN-HEADEREND:event_yawDerivateTextFieldFocusLost
        yawDerivateTextField.setText("Derivate: " + regulator.getKdYaw());
    }//GEN-LAST:event_yawDerivateTextFieldFocusLost

    private void snapshotButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_snapshotButtonActionPerformed
    {//GEN-HEADEREND:event_snapshotButtonActionPerformed
        try {
            File outputfile = new File("saved.png");
            ImageIO.write(v1.getImage(), "png", outputfile);
        }
        catch (IOException e) {
        }
    }//GEN-LAST:event_snapshotButtonActionPerformed

    private void hueLowerTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_hueLowerTFActionPerformed
    {//GEN-HEADEREND:event_hueLowerTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hueLowerTFActionPerformed

    private void hueUpperTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_hueUpperTFActionPerformed
    {//GEN-HEADEREND:event_hueUpperTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hueUpperTFActionPerformed

    private void SaturationLowerTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaturationLowerTFActionPerformed
    {//GEN-HEADEREND:event_SaturationLowerTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaturationLowerTFActionPerformed

    private void saturationUpperTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saturationUpperTFActionPerformed
    {//GEN-HEADEREND:event_saturationUpperTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saturationUpperTFActionPerformed

    private void valueLowerTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_valueLowerTFActionPerformed
    {//GEN-HEADEREND:event_valueLowerTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueLowerTFActionPerformed

    private void valueUpperTFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_valueUpperTFActionPerformed
    {//GEN-HEADEREND:event_valueUpperTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueUpperTFActionPerformed

    private void hueLowerTFFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_hueLowerTFFocusGained
    {//GEN-HEADEREND:event_hueLowerTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_hueLowerTFFocusGained

    private void hueUpperTFFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_hueUpperTFFocusGained
    {//GEN-HEADEREND:event_hueUpperTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_hueUpperTFFocusGained

    private void SaturationLowerTFFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_SaturationLowerTFFocusGained
    {//GEN-HEADEREND:event_SaturationLowerTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_SaturationLowerTFFocusGained

    private void saturationUpperTFFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_saturationUpperTFFocusGained
    {//GEN-HEADEREND:event_saturationUpperTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_saturationUpperTFFocusGained

    private void valueLowerTFFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_valueLowerTFFocusGained
    {//GEN-HEADEREND:event_valueLowerTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_valueLowerTFFocusGained

    private void valueUpperTFFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_valueUpperTFFocusGained
    {//GEN-HEADEREND:event_valueUpperTFFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_valueUpperTFFocusGained

    private void hueLowerTFFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_hueLowerTFFocusLost
    {//GEN-HEADEREND:event_hueLowerTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_hueLowerTFFocusLost

    private void hueUpperTFFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_hueUpperTFFocusLost
    {//GEN-HEADEREND:event_hueUpperTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_hueUpperTFFocusLost

    private void SaturationLowerTFFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_SaturationLowerTFFocusLost
    {//GEN-HEADEREND:event_SaturationLowerTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_SaturationLowerTFFocusLost

    private void saturationUpperTFFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_saturationUpperTFFocusLost
    {//GEN-HEADEREND:event_saturationUpperTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_saturationUpperTFFocusLost

    private void valueUpperTFFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_valueUpperTFFocusLost
    {//GEN-HEADEREND:event_valueUpperTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_valueUpperTFFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel1;
    private javax.swing.JPanel ImageProcessViewer;
    private javax.swing.JTextField SaturationLowerTF;
    private javax.swing.JPanel VideoStreamViewer;
    private javax.swing.JTextField altitudeTextField;
    private javax.swing.JButton autoButton;
    private javax.swing.JTextField batTextField;
    private javax.swing.JTextField hueLowerTF;
    private javax.swing.JTextField hueUpperTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton landButton;
    private javax.swing.JButton manButton;
    private javax.swing.JTextField pitchTextField;
    private javax.swing.JTextField rollTextField;
    private javax.swing.JTextField saturationUpperTF;
    private javax.swing.JButton snapshotButton;
    private javax.swing.JTextField valueLowerTF;
    private javax.swing.JTextField valueUpperTF;
    private javax.swing.JTextField yawDerivateTextField;
    private javax.swing.JTextField yawIntegralTextField;
    private javax.swing.JTextField yawPropotionalTextField;
    private javax.swing.JTextField yawTextField;
    // End of variables declaration//GEN-END:variables

    // Ikke-autogenererte metoder
    private void repaintTextFields()
    {
        rollTextField.repaint();
        pitchTextField.repaint();
        yawTextField.repaint();
        altitudeTextField.repaint();
        batTextField.repaint();
    }

    public void run()
    {

        while (true) {
            rollTextField.setText("Roll: " + navData.getRoll());
            pitchTextField.setText("Pitch: " + navData.getPitch());
            yawTextField.setText("Yaw: " + navData.getYaw());
            altitudeTextField.setText("Altitude: " + navData.getExtAltitude().getRaw() / 1000f);
            batTextField.setText("Battery status : " + navData.getPercentage() + "%");
            repaintTextFields();
        }

    }

}
